// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proxy/hysteria2/config.proto

package hysteria2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InboundConfig keeps Hysteria2 server settings.
type InboundConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw Hysteria2 server configuration. The schema matches the original
	// Hysteria2 JSON/YAML config. Extra Xray-only tweaks can be placed under
	// the optional "xray" object and are stripped before handing to Hysteria.
	Settings      *structpb.Struct `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundConfig) Reset() {
	*x = InboundConfig{}
	mi := &file_proxy_hysteria2_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundConfig) ProtoMessage() {}

func (x *InboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_hysteria2_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundConfig.ProtoReflect.Descriptor instead.
func (*InboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_hysteria2_config_proto_rawDescGZIP(), []int{0}
}

func (x *InboundConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

// OutboundConfig keeps Hysteria2 client settings.
type OutboundConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw Hysteria2 client configuration. Schema follows upstream Hysteria2
	// config format.
	Settings      *structpb.Struct `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundConfig) Reset() {
	*x = OutboundConfig{}
	mi := &file_proxy_hysteria2_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundConfig) ProtoMessage() {}

func (x *OutboundConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_hysteria2_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundConfig.ProtoReflect.Descriptor instead.
func (*OutboundConfig) Descriptor() ([]byte, []int) {
	return file_proxy_hysteria2_config_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundConfig) GetSettings() *structpb.Struct {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_proxy_hysteria2_config_proto protoreflect.FileDescriptor

const file_proxy_hysteria2_config_proto_rawDesc = "" +
	"\n" +
	"\x1cproxy/hysteria2/config.proto\x12\x14xray.proxy.hysteria2\x1a\x1cgoogle/protobuf/struct.proto\"D\n" +
	"\rInboundConfig\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettings\"E\n" +
	"\x0eOutboundConfig\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bsettingsB^\n" +
	"\x18com.xray.proxy.hysteria2P\x01Z)github.com/xtls/xray-core/proxy/hysteria2\xaa\x02\x14Xray.Proxy.Hysteria2b\x06proto3"

var (
	file_proxy_hysteria2_config_proto_rawDescOnce sync.Once
	file_proxy_hysteria2_config_proto_rawDescData []byte
)

func file_proxy_hysteria2_config_proto_rawDescGZIP() []byte {
	file_proxy_hysteria2_config_proto_rawDescOnce.Do(func() {
		file_proxy_hysteria2_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_hysteria2_config_proto_rawDesc), len(file_proxy_hysteria2_config_proto_rawDesc)))
	})
	return file_proxy_hysteria2_config_proto_rawDescData
}

var file_proxy_hysteria2_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_hysteria2_config_proto_goTypes = []any{
	(*InboundConfig)(nil),   // 0: xray.proxy.hysteria2.InboundConfig
	(*OutboundConfig)(nil),  // 1: xray.proxy.hysteria2.OutboundConfig
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_proxy_hysteria2_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.hysteria2.InboundConfig.settings:type_name -> google.protobuf.Struct
	2, // 1: xray.proxy.hysteria2.OutboundConfig.settings:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_hysteria2_config_proto_init() }
func file_proxy_hysteria2_config_proto_init() {
	if File_proxy_hysteria2_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_hysteria2_config_proto_rawDesc), len(file_proxy_hysteria2_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_hysteria2_config_proto_goTypes,
		DependencyIndexes: file_proxy_hysteria2_config_proto_depIdxs,
		MessageInfos:      file_proxy_hysteria2_config_proto_msgTypes,
	}.Build()
	File_proxy_hysteria2_config_proto = out.File
	file_proxy_hysteria2_config_proto_goTypes = nil
	file_proxy_hysteria2_config_proto_depIdxs = nil
}
