// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: proxy/freedom/config.proto

package freedom

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_DomainStrategy int32

const (
	Config_AS_IS      Config_DomainStrategy = 0
	Config_USE_IP     Config_DomainStrategy = 1
	Config_USE_IP4    Config_DomainStrategy = 2
	Config_USE_IP6    Config_DomainStrategy = 3
	Config_USE_IP46   Config_DomainStrategy = 4
	Config_USE_IP64   Config_DomainStrategy = 5
	Config_FORCE_IP   Config_DomainStrategy = 6
	Config_FORCE_IP4  Config_DomainStrategy = 7
	Config_FORCE_IP6  Config_DomainStrategy = 8
	Config_FORCE_IP46 Config_DomainStrategy = 9
	Config_FORCE_IP64 Config_DomainStrategy = 10
)

// Enum value maps for Config_DomainStrategy.
var (
	Config_DomainStrategy_name = map[int32]string{
		0:  "AS_IS",
		1:  "USE_IP",
		2:  "USE_IP4",
		3:  "USE_IP6",
		4:  "USE_IP46",
		5:  "USE_IP64",
		6:  "FORCE_IP",
		7:  "FORCE_IP4",
		8:  "FORCE_IP6",
		9:  "FORCE_IP46",
		10: "FORCE_IP64",
	}
	Config_DomainStrategy_value = map[string]int32{
		"AS_IS":      0,
		"USE_IP":     1,
		"USE_IP4":    2,
		"USE_IP6":    3,
		"USE_IP46":   4,
		"USE_IP64":   5,
		"FORCE_IP":   6,
		"FORCE_IP4":  7,
		"FORCE_IP6":  8,
		"FORCE_IP46": 9,
		"FORCE_IP64": 10,
	}
)

func (x Config_DomainStrategy) Enum() *Config_DomainStrategy {
	p := new(Config_DomainStrategy)
	*p = x
	return p
}

func (x Config_DomainStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_DomainStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_freedom_config_proto_enumTypes[0].Descriptor()
}

func (Config_DomainStrategy) Type() protoreflect.EnumType {
	return &file_proxy_freedom_config_proto_enumTypes[0]
}

func (x Config_DomainStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_DomainStrategy.Descriptor instead.
func (Config_DomainStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proxy_freedom_config_proto_rawDescGZIP(), []int{3, 0}
}

type DestinationOverride struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestinationOverride) Reset() {
	*x = DestinationOverride{}
	mi := &file_proxy_freedom_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestinationOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestinationOverride) ProtoMessage() {}

func (x *DestinationOverride) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_freedom_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestinationOverride.ProtoReflect.Descriptor instead.
func (*DestinationOverride) Descriptor() ([]byte, []int) {
	return file_proxy_freedom_config_proto_rawDescGZIP(), []int{0}
}

func (x *DestinationOverride) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

type Fragment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketsFrom   uint64                 `protobuf:"varint,1,opt,name=packets_from,json=packetsFrom,proto3" json:"packets_from,omitempty"`
	PacketsTo     uint64                 `protobuf:"varint,2,opt,name=packets_to,json=packetsTo,proto3" json:"packets_to,omitempty"`
	LengthMin     uint64                 `protobuf:"varint,3,opt,name=length_min,json=lengthMin,proto3" json:"length_min,omitempty"`
	LengthMax     uint64                 `protobuf:"varint,4,opt,name=length_max,json=lengthMax,proto3" json:"length_max,omitempty"`
	IntervalMin   uint64                 `protobuf:"varint,5,opt,name=interval_min,json=intervalMin,proto3" json:"interval_min,omitempty"`
	IntervalMax   uint64                 `protobuf:"varint,6,opt,name=interval_max,json=intervalMax,proto3" json:"interval_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fragment) Reset() {
	*x = Fragment{}
	mi := &file_proxy_freedom_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fragment) ProtoMessage() {}

func (x *Fragment) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_freedom_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fragment.ProtoReflect.Descriptor instead.
func (*Fragment) Descriptor() ([]byte, []int) {
	return file_proxy_freedom_config_proto_rawDescGZIP(), []int{1}
}

func (x *Fragment) GetPacketsFrom() uint64 {
	if x != nil {
		return x.PacketsFrom
	}
	return 0
}

func (x *Fragment) GetPacketsTo() uint64 {
	if x != nil {
		return x.PacketsTo
	}
	return 0
}

func (x *Fragment) GetLengthMin() uint64 {
	if x != nil {
		return x.LengthMin
	}
	return 0
}

func (x *Fragment) GetLengthMax() uint64 {
	if x != nil {
		return x.LengthMax
	}
	return 0
}

func (x *Fragment) GetIntervalMin() uint64 {
	if x != nil {
		return x.IntervalMin
	}
	return 0
}

func (x *Fragment) GetIntervalMax() uint64 {
	if x != nil {
		return x.IntervalMax
	}
	return 0
}

type Noise struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LengthMin     uint64                 `protobuf:"varint,1,opt,name=length_min,json=lengthMin,proto3" json:"length_min,omitempty"`
	LengthMax     uint64                 `protobuf:"varint,2,opt,name=length_max,json=lengthMax,proto3" json:"length_max,omitempty"`
	DelayMin      uint64                 `protobuf:"varint,3,opt,name=delay_min,json=delayMin,proto3" json:"delay_min,omitempty"`
	DelayMax      uint64                 `protobuf:"varint,4,opt,name=delay_max,json=delayMax,proto3" json:"delay_max,omitempty"`
	Packet        []byte                 `protobuf:"bytes,5,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noise) Reset() {
	*x = Noise{}
	mi := &file_proxy_freedom_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noise) ProtoMessage() {}

func (x *Noise) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_freedom_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noise.ProtoReflect.Descriptor instead.
func (*Noise) Descriptor() ([]byte, []int) {
	return file_proxy_freedom_config_proto_rawDescGZIP(), []int{2}
}

func (x *Noise) GetLengthMin() uint64 {
	if x != nil {
		return x.LengthMin
	}
	return 0
}

func (x *Noise) GetLengthMax() uint64 {
	if x != nil {
		return x.LengthMax
	}
	return 0
}

func (x *Noise) GetDelayMin() uint64 {
	if x != nil {
		return x.DelayMin
	}
	return 0
}

func (x *Noise) GetDelayMax() uint64 {
	if x != nil {
		return x.DelayMax
	}
	return 0
}

func (x *Noise) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

type Config struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DomainStrategy      Config_DomainStrategy  `protobuf:"varint,1,opt,name=domain_strategy,json=domainStrategy,proto3,enum=xray.proxy.freedom.Config_DomainStrategy" json:"domain_strategy,omitempty"`
	DestinationOverride *DestinationOverride   `protobuf:"bytes,3,opt,name=destination_override,json=destinationOverride,proto3" json:"destination_override,omitempty"`
	UserLevel           uint32                 `protobuf:"varint,4,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	Fragment            *Fragment              `protobuf:"bytes,5,opt,name=fragment,proto3" json:"fragment,omitempty"`
	ProxyProtocol       uint32                 `protobuf:"varint,6,opt,name=proxy_protocol,json=proxyProtocol,proto3" json:"proxy_protocol,omitempty"`
	Noises              []*Noise               `protobuf:"bytes,7,rep,name=noises,proto3" json:"noises,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_freedom_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_freedom_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_freedom_config_proto_rawDescGZIP(), []int{3}
}

func (x *Config) GetDomainStrategy() Config_DomainStrategy {
	if x != nil {
		return x.DomainStrategy
	}
	return Config_AS_IS
}

func (x *Config) GetDestinationOverride() *DestinationOverride {
	if x != nil {
		return x.DestinationOverride
	}
	return nil
}

func (x *Config) GetUserLevel() uint32 {
	if x != nil {
		return x.UserLevel
	}
	return 0
}

func (x *Config) GetFragment() *Fragment {
	if x != nil {
		return x.Fragment
	}
	return nil
}

func (x *Config) GetProxyProtocol() uint32 {
	if x != nil {
		return x.ProxyProtocol
	}
	return 0
}

func (x *Config) GetNoises() []*Noise {
	if x != nil {
		return x.Noises
	}
	return nil
}

var File_proxy_freedom_config_proto protoreflect.FileDescriptor

const file_proxy_freedom_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/freedom/config.proto\x12\x12xray.proxy.freedom\x1a!common/protocol/server_spec.proto\"S\n" +
	"\x13DestinationOverride\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06server\"\xd0\x01\n" +
	"\bFragment\x12!\n" +
	"\fpackets_from\x18\x01 \x01(\x04R\vpacketsFrom\x12\x1d\n" +
	"\n" +
	"packets_to\x18\x02 \x01(\x04R\tpacketsTo\x12\x1d\n" +
	"\n" +
	"length_min\x18\x03 \x01(\x04R\tlengthMin\x12\x1d\n" +
	"\n" +
	"length_max\x18\x04 \x01(\x04R\tlengthMax\x12!\n" +
	"\finterval_min\x18\x05 \x01(\x04R\vintervalMin\x12!\n" +
	"\finterval_max\x18\x06 \x01(\x04R\vintervalMax\"\x97\x01\n" +
	"\x05Noise\x12\x1d\n" +
	"\n" +
	"length_min\x18\x01 \x01(\x04R\tlengthMin\x12\x1d\n" +
	"\n" +
	"length_max\x18\x02 \x01(\x04R\tlengthMax\x12\x1b\n" +
	"\tdelay_min\x18\x03 \x01(\x04R\bdelayMin\x12\x1b\n" +
	"\tdelay_max\x18\x04 \x01(\x04R\bdelayMax\x12\x16\n" +
	"\x06packet\x18\x05 \x01(\fR\x06packet\"\x97\x04\n" +
	"\x06Config\x12R\n" +
	"\x0fdomain_strategy\x18\x01 \x01(\x0e2).xray.proxy.freedom.Config.DomainStrategyR\x0edomainStrategy\x12Z\n" +
	"\x14destination_override\x18\x03 \x01(\v2'.xray.proxy.freedom.DestinationOverrideR\x13destinationOverride\x12\x1d\n" +
	"\n" +
	"user_level\x18\x04 \x01(\rR\tuserLevel\x128\n" +
	"\bfragment\x18\x05 \x01(\v2\x1c.xray.proxy.freedom.FragmentR\bfragment\x12%\n" +
	"\x0eproxy_protocol\x18\x06 \x01(\rR\rproxyProtocol\x121\n" +
	"\x06noises\x18\a \x03(\v2\x19.xray.proxy.freedom.NoiseR\x06noises\"\xa9\x01\n" +
	"\x0eDomainStrategy\x12\t\n" +
	"\x05AS_IS\x10\x00\x12\n" +
	"\n" +
	"\x06USE_IP\x10\x01\x12\v\n" +
	"\aUSE_IP4\x10\x02\x12\v\n" +
	"\aUSE_IP6\x10\x03\x12\f\n" +
	"\bUSE_IP46\x10\x04\x12\f\n" +
	"\bUSE_IP64\x10\x05\x12\f\n" +
	"\bFORCE_IP\x10\x06\x12\r\n" +
	"\tFORCE_IP4\x10\a\x12\r\n" +
	"\tFORCE_IP6\x10\b\x12\x0e\n" +
	"\n" +
	"FORCE_IP46\x10\t\x12\x0e\n" +
	"\n" +
	"FORCE_IP64\x10\n" +
	"BX\n" +
	"\x16com.xray.proxy.freedomP\x01Z'github.com/xtls/xray-core/proxy/freedom\xaa\x02\x12Xray.Proxy.Freedomb\x06proto3"

var (
	file_proxy_freedom_config_proto_rawDescOnce sync.Once
	file_proxy_freedom_config_proto_rawDescData []byte
)

func file_proxy_freedom_config_proto_rawDescGZIP() []byte {
	file_proxy_freedom_config_proto_rawDescOnce.Do(func() {
		file_proxy_freedom_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_freedom_config_proto_rawDesc), len(file_proxy_freedom_config_proto_rawDesc)))
	})
	return file_proxy_freedom_config_proto_rawDescData
}

var file_proxy_freedom_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_freedom_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proxy_freedom_config_proto_goTypes = []any{
	(Config_DomainStrategy)(0),      // 0: xray.proxy.freedom.Config.DomainStrategy
	(*DestinationOverride)(nil),     // 1: xray.proxy.freedom.DestinationOverride
	(*Fragment)(nil),                // 2: xray.proxy.freedom.Fragment
	(*Noise)(nil),                   // 3: xray.proxy.freedom.Noise
	(*Config)(nil),                  // 4: xray.proxy.freedom.Config
	(*protocol.ServerEndpoint)(nil), // 5: xray.common.protocol.ServerEndpoint
}
var file_proxy_freedom_config_proto_depIdxs = []int32{
	5, // 0: xray.proxy.freedom.DestinationOverride.server:type_name -> xray.common.protocol.ServerEndpoint
	0, // 1: xray.proxy.freedom.Config.domain_strategy:type_name -> xray.proxy.freedom.Config.DomainStrategy
	1, // 2: xray.proxy.freedom.Config.destination_override:type_name -> xray.proxy.freedom.DestinationOverride
	2, // 3: xray.proxy.freedom.Config.fragment:type_name -> xray.proxy.freedom.Fragment
	3, // 4: xray.proxy.freedom.Config.noises:type_name -> xray.proxy.freedom.Noise
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proxy_freedom_config_proto_init() }
func file_proxy_freedom_config_proto_init() {
	if File_proxy_freedom_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_freedom_config_proto_rawDesc), len(file_proxy_freedom_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_freedom_config_proto_goTypes,
		DependencyIndexes: file_proxy_freedom_config_proto_depIdxs,
		EnumInfos:         file_proxy_freedom_config_proto_enumTypes,
		MessageInfos:      file_proxy_freedom_config_proto_msgTypes,
	}.Build()
	File_proxy_freedom_config_proto = out.File
	file_proxy_freedom_config_proto_goTypes = nil
	file_proxy_freedom_config_proto_depIdxs = nil
}
