// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/ssh/config.proto

package ssh

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Username             string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PrivateKey           string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PrivateKeyPassphrase string                 `protobuf:"bytes,4,opt,name=private_key_passphrase,json=privateKeyPassphrase,proto3" json:"private_key_passphrase,omitempty"`
	HostKeySha256        string                 `protobuf:"bytes,5,opt,name=host_key_sha256,json=hostKeySha256,proto3" json:"host_key_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_ssh_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Account) GetPrivateKeyPassphrase() string {
	if x != nil {
		return x.PrivateKeyPassphrase
	}
	return ""
}

func (x *Account) GetHostKeySha256() string {
	if x != nil {
		return x.HostKeySha256
	}
	return ""
}

type ClientConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_ssh_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_ssh_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_ssh_config_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_proxy_ssh_config_proto protoreflect.FileDescriptor

const file_proxy_ssh_config_proto_rawDesc = "" +
	"\n" +
	"\x16proxy/ssh/config.proto\x12\x0exray.proxy.ssh\x1a!common/protocol/server_spec.proto\"\xc0\x01\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x124\n" +
	"\x16private_key_passphrase\x18\x04 \x01(\tR\x14privateKeyPassphrase\x12&\n" +
	"\x0fhost_key_sha256\x18\x05 \x01(\tR\rhostKeySha256\"L\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06serverBL\n" +
	"\x12com.xray.proxy.sshP\x01Z#github.com/xtls/xray-core/proxy/ssh\xaa\x02\x0eXray.Proxy.Sshb\x06proto3"

var (
	file_proxy_ssh_config_proto_rawDescOnce sync.Once
	file_proxy_ssh_config_proto_rawDescData []byte
)

func file_proxy_ssh_config_proto_rawDescGZIP() []byte {
	file_proxy_ssh_config_proto_rawDescOnce.Do(func() {
		file_proxy_ssh_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_ssh_config_proto_rawDesc), len(file_proxy_ssh_config_proto_rawDesc)))
	})
	return file_proxy_ssh_config_proto_rawDescData
}

var file_proxy_ssh_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_ssh_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.ssh.Account
	(*ClientConfig)(nil),            // 1: xray.proxy.ssh.ClientConfig
	(*protocol.ServerEndpoint)(nil), // 2: xray.common.protocol.ServerEndpoint
}
var file_proxy_ssh_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.ssh.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_ssh_config_proto_init() }
func file_proxy_ssh_config_proto_init() {
	if File_proxy_ssh_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_ssh_config_proto_rawDesc), len(file_proxy_ssh_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_ssh_config_proto_goTypes,
		DependencyIndexes: file_proxy_ssh_config_proto_depIdxs,
		MessageInfos:      file_proxy_ssh_config_proto_msgTypes,
	}.Build()
	File_proxy_ssh_config_proto = out.File
	file_proxy_ssh_config_proto_goTypes = nil
	file_proxy_ssh_config_proto_depIdxs = nil
}
