// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transport/internet/hysteria/config.proto

package hysteria

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Auth                 string                 `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	UdpIdleTimeout       int64                  `protobuf:"varint,3,opt,name=udp_idle_timeout,json=udpIdleTimeout,proto3" json:"udp_idle_timeout,omitempty"`
	MasqType             string                 `protobuf:"bytes,4,opt,name=masq_type,json=masqType,proto3" json:"masq_type,omitempty"`
	MasqFile             string                 `protobuf:"bytes,5,opt,name=masq_file,json=masqFile,proto3" json:"masq_file,omitempty"`
	MasqUrl              string                 `protobuf:"bytes,6,opt,name=masq_url,json=masqUrl,proto3" json:"masq_url,omitempty"`
	MasqUrlRewriteHost   bool                   `protobuf:"varint,7,opt,name=masq_url_rewrite_host,json=masqUrlRewriteHost,proto3" json:"masq_url_rewrite_host,omitempty"`
	MasqUrlInsecure      bool                   `protobuf:"varint,8,opt,name=masq_url_insecure,json=masqUrlInsecure,proto3" json:"masq_url_insecure,omitempty"`
	MasqString           string                 `protobuf:"bytes,9,opt,name=masq_string,json=masqString,proto3" json:"masq_string,omitempty"`
	MasqStringHeaders    map[string]string      `protobuf:"bytes,10,rep,name=masq_string_headers,json=masqStringHeaders,proto3" json:"masq_string_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MasqStringStatusCode int32                  `protobuf:"varint,11,opt,name=masq_string_status_code,json=masqStringStatusCode,proto3" json:"masq_string_status_code,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_hysteria_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_hysteria_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_hysteria_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Config) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *Config) GetUdpIdleTimeout() int64 {
	if x != nil {
		return x.UdpIdleTimeout
	}
	return 0
}

func (x *Config) GetMasqType() string {
	if x != nil {
		return x.MasqType
	}
	return ""
}

func (x *Config) GetMasqFile() string {
	if x != nil {
		return x.MasqFile
	}
	return ""
}

func (x *Config) GetMasqUrl() string {
	if x != nil {
		return x.MasqUrl
	}
	return ""
}

func (x *Config) GetMasqUrlRewriteHost() bool {
	if x != nil {
		return x.MasqUrlRewriteHost
	}
	return false
}

func (x *Config) GetMasqUrlInsecure() bool {
	if x != nil {
		return x.MasqUrlInsecure
	}
	return false
}

func (x *Config) GetMasqString() string {
	if x != nil {
		return x.MasqString
	}
	return ""
}

func (x *Config) GetMasqStringHeaders() map[string]string {
	if x != nil {
		return x.MasqStringHeaders
	}
	return nil
}

func (x *Config) GetMasqStringStatusCode() int32 {
	if x != nil {
		return x.MasqStringStatusCode
	}
	return 0
}

var File_transport_internet_hysteria_config_proto protoreflect.FileDescriptor

const file_transport_internet_hysteria_config_proto_rawDesc = "" +
	"\n" +
	"(transport/internet/hysteria/config.proto\x12 xray.transport.internet.hysteria\"\xa3\x04\n" +
	"\x06Config\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\tR\x04auth\x12(\n" +
	"\x10udp_idle_timeout\x18\x03 \x01(\x03R\x0eudpIdleTimeout\x12\x1b\n" +
	"\tmasq_type\x18\x04 \x01(\tR\bmasqType\x12\x1b\n" +
	"\tmasq_file\x18\x05 \x01(\tR\bmasqFile\x12\x19\n" +
	"\bmasq_url\x18\x06 \x01(\tR\amasqUrl\x121\n" +
	"\x15masq_url_rewrite_host\x18\a \x01(\bR\x12masqUrlRewriteHost\x12*\n" +
	"\x11masq_url_insecure\x18\b \x01(\bR\x0fmasqUrlInsecure\x12\x1f\n" +
	"\vmasq_string\x18\t \x01(\tR\n" +
	"masqString\x12o\n" +
	"\x13masq_string_headers\x18\n" +
	" \x03(\v2?.xray.transport.internet.hysteria.Config.MasqStringHeadersEntryR\x11masqStringHeaders\x125\n" +
	"\x17masq_string_status_code\x18\v \x01(\x05R\x14masqStringStatusCode\x1aD\n" +
	"\x16MasqStringHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x82\x01\n" +
	"$com.xray.transport.internet.hysteriaP\x01Z5github.com/xtls/xray-core/transport/internet/hysteria\xaa\x02 Xray.Transport.Internet.Hysteriab\x06proto3"

var (
	file_transport_internet_hysteria_config_proto_rawDescOnce sync.Once
	file_transport_internet_hysteria_config_proto_rawDescData []byte
)

func file_transport_internet_hysteria_config_proto_rawDescGZIP() []byte {
	file_transport_internet_hysteria_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_hysteria_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_hysteria_config_proto_rawDesc), len(file_transport_internet_hysteria_config_proto_rawDesc)))
	})
	return file_transport_internet_hysteria_config_proto_rawDescData
}

var file_transport_internet_hysteria_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_internet_hysteria_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.hysteria.Config
	nil,            // 1: xray.transport.internet.hysteria.Config.MasqStringHeadersEntry
}
var file_transport_internet_hysteria_config_proto_depIdxs = []int32{
	1, // 0: xray.transport.internet.hysteria.Config.masq_string_headers:type_name -> xray.transport.internet.hysteria.Config.MasqStringHeadersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transport_internet_hysteria_config_proto_init() }
func file_transport_internet_hysteria_config_proto_init() {
	if File_transport_internet_hysteria_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_hysteria_config_proto_rawDesc), len(file_transport_internet_hysteria_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_hysteria_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_hysteria_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_hysteria_config_proto_msgTypes,
	}.Build()
	File_transport_internet_hysteria_config_proto = out.File
	file_transport_internet_hysteria_config_proto_goTypes = nil
	file_transport_internet_hysteria_config_proto_depIdxs = nil
}
