// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transport/internet/finalmask/rawpacket/config.proto

package rawpacket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mode: "local" (client) or "remote" (server).
	Mode string `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	// Remote server address (local/client mode).
	RemoteAddress string `protobuf:"bytes,7,opt,name=remote_address,json=remoteAddress,proto3" json:"remote_address,omitempty"`
	// Remote server port (client mode).
	RemotePort uint32 `protobuf:"varint,8,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	// Local port for receiving responses from the relay (client mode).
	RecvPort uint32 `protobuf:"varint,9,opt,name=recv_port,json=recvPort,proto3" json:"recv_port,omitempty"`
	// List of IP addresses to spoof as source.
	SpoofIps []string `protobuf:"bytes,10,rep,name=spoof_ips,json=spoofIps,proto3" json:"spoof_ips,omitempty"`
	// List of transport protocols to use: tcp, udp, icmp, icmpv6.
	Protocols []string `protobuf:"bytes,11,rep,name=protocols,proto3" json:"protocols,omitempty"`
	// MTU for packet fragmentation.
	Mtu uint32 `protobuf:"varint,12,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Target address for the relay (e.g. "127.0.0.1:443").
	Target string `protobuf:"bytes,13,opt,name=target,proto3" json:"target,omitempty"`
	// TTL for outgoing packets.
	Ttl uint32 `protobuf:"varint,14,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Send transport: "tcp", "udp", "icmp", "icmpv6" (default: "tcp").
	SendTransport string `protobuf:"bytes,15,opt,name=send_transport,json=sendTransport,proto3" json:"send_transport,omitempty"`
	// Receive transport: "tcp", "udp", "icmp", "icmpv6" (default: "udp").
	RecvTransport string `protobuf:"bytes,16,opt,name=recv_transport,json=recvTransport,proto3" json:"recv_transport,omitempty"`
	// Relay address (for the relay sender, defaults to first spoof IP).
	RelayAddress string `protobuf:"bytes,17,opt,name=relay_address,json=relayAddress,proto3" json:"relay_address,omitempty"`
	// Port the relay listens on (remote/server mode).
	RelayPort uint32 `protobuf:"varint,18,opt,name=relay_port,json=relayPort,proto3" json:"relay_port,omitempty"`
	// Client IP address (remote/server mode) — where to send responses.
	ClientIp string `protobuf:"bytes,19,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	// Client port (remote/server mode).
	ClientPort uint32 `protobuf:"varint,20,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	// Expected peer spoof IP for receive filtering (nil = accept all).
	PeerSpoofIp string `protobuf:"bytes,21,opt,name=peer_spoof_ip,json=peerSpoofIp,proto3" json:"peer_spoof_ip,omitempty"`
	// Source port to use in spoofed packets (default: 443).
	SpoofPort     uint32 `protobuf:"varint,22,opt,name=spoof_port,json=spoofPort,proto3" json:"spoof_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_finalmask_rawpacket_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_rawpacket_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_rawpacket_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Config) GetRemoteAddress() string {
	if x != nil {
		return x.RemoteAddress
	}
	return ""
}

func (x *Config) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *Config) GetRecvPort() uint32 {
	if x != nil {
		return x.RecvPort
	}
	return 0
}

func (x *Config) GetSpoofIps() []string {
	if x != nil {
		return x.SpoofIps
	}
	return nil
}

func (x *Config) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *Config) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Config) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Config) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Config) GetSendTransport() string {
	if x != nil {
		return x.SendTransport
	}
	return ""
}

func (x *Config) GetRecvTransport() string {
	if x != nil {
		return x.RecvTransport
	}
	return ""
}

func (x *Config) GetRelayAddress() string {
	if x != nil {
		return x.RelayAddress
	}
	return ""
}

func (x *Config) GetRelayPort() uint32 {
	if x != nil {
		return x.RelayPort
	}
	return 0
}

func (x *Config) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *Config) GetClientPort() uint32 {
	if x != nil {
		return x.ClientPort
	}
	return 0
}

func (x *Config) GetPeerSpoofIp() string {
	if x != nil {
		return x.PeerSpoofIp
	}
	return ""
}

func (x *Config) GetSpoofPort() uint32 {
	if x != nil {
		return x.SpoofPort
	}
	return 0
}

var File_transport_internet_finalmask_rawpacket_config_proto protoreflect.FileDescriptor

const file_transport_internet_finalmask_rawpacket_config_proto_rawDesc = "" +
	"\n" +
	"3transport/internet/finalmask/rawpacket/config.proto\x12+xray.transport.internet.finalmask.rawpacket\"\x8b\x04\n" +
	"\x06Config\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12%\n" +
	"\x0eremote_address\x18\a \x01(\tR\rremoteAddress\x12\x1f\n" +
	"\vremote_port\x18\b \x01(\rR\n" +
	"remotePort\x12\x1b\n" +
	"\trecv_port\x18\t \x01(\rR\brecvPort\x12\x1b\n" +
	"\tspoof_ips\x18\n" +
	" \x03(\tR\bspoofIps\x12\x1c\n" +
	"\tprotocols\x18\v \x03(\tR\tprotocols\x12\x10\n" +
	"\x03mtu\x18\f \x01(\rR\x03mtu\x12\x16\n" +
	"\x06target\x18\r \x01(\tR\x06target\x12\x10\n" +
	"\x03ttl\x18\x0e \x01(\rR\x03ttl\x12%\n" +
	"\x0esend_transport\x18\x0f \x01(\tR\rsendTransport\x12%\n" +
	"\x0erecv_transport\x18\x10 \x01(\tR\rrecvTransport\x12#\n" +
	"\rrelay_address\x18\x11 \x01(\tR\frelayAddress\x12\x1d\n" +
	"\n" +
	"relay_port\x18\x12 \x01(\rR\trelayPort\x12\x1b\n" +
	"\tclient_ip\x18\x13 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x14 \x01(\rR\n" +
	"clientPort\x12\"\n" +
	"\rpeer_spoof_ip\x18\x15 \x01(\tR\vpeerSpoofIp\x12\x1d\n" +
	"\n" +
	"spoof_port\x18\x16 \x01(\rR\tspoofPortB\xa3\x01\n" +
	"/com.xray.transport.internet.finalmask.rawpacketP\x01Z@github.com/xtls/xray-core/transport/internet/finalmask/rawpacket\xaa\x02+Xray.Transport.Internet.Finalmask.Rawpacketb\x06proto3"

var (
	file_transport_internet_finalmask_rawpacket_config_proto_rawDescOnce sync.Once
	file_transport_internet_finalmask_rawpacket_config_proto_rawDescData []byte
)

func file_transport_internet_finalmask_rawpacket_config_proto_rawDescGZIP() []byte {
	file_transport_internet_finalmask_rawpacket_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_finalmask_rawpacket_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_finalmask_rawpacket_config_proto_rawDesc), len(file_transport_internet_finalmask_rawpacket_config_proto_rawDesc)))
	})
	return file_transport_internet_finalmask_rawpacket_config_proto_rawDescData
}

var file_transport_internet_finalmask_rawpacket_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_finalmask_rawpacket_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.finalmask.rawpacket.Config
}
var file_transport_internet_finalmask_rawpacket_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_finalmask_rawpacket_config_proto_init() }
func file_transport_internet_finalmask_rawpacket_config_proto_init() {
	if File_transport_internet_finalmask_rawpacket_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_finalmask_rawpacket_config_proto_rawDesc), len(file_transport_internet_finalmask_rawpacket_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_finalmask_rawpacket_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_finalmask_rawpacket_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_finalmask_rawpacket_config_proto_msgTypes,
	}.Build()
	File_transport_internet_finalmask_rawpacket_config_proto = out.File
	file_transport_internet_finalmask_rawpacket_config_proto_goTypes = nil
	file_transport_internet_finalmask_rawpacket_config_proto_depIdxs = nil
}
