name: bugåé¦ˆ
description: "æäº¤ Xray-core bug"
body:
  - type: checkboxes
    attributes:
      label: å®Œæ•´æ€§è¦æ±?      description: |-
        è¯·å‹¾é€‰ä»¥ä¸‹æ‰€æœ‰é€‰é¡¹ä»¥è¯æ˜æ‚¨å·²ç»é˜…è¯»å¹¶ç†è§£äº†ä»¥ä¸‹è¦æ±‚ï¼Œå¦åˆ™è¯¥ issue å°†è¢«å…³é—­ã€?      options:
        - label: æˆ‘ä¿è¯é˜…è¯»äº†æ–‡æ¡£ï¼Œäº†è§£æ‰€æœ‰æˆ‘ç¼–å†™çš„é…ç½®æ–‡ä»¶é¡¹çš„å«ä¹‰ï¼Œè€Œä¸æ˜¯å¤§é‡å †ç Œçœ‹ä¼¼æœ‰ç”¨çš„é€‰é¡¹æˆ–é»˜è®¤å€¼ã€?          required: true
        - label: æˆ‘æä¾›äº†å®Œæ•´çš„é…ç½®æ–‡ä»¶å’Œæ—¥å¿—ï¼Œè€Œä¸æ˜¯å‡ºäºè‡ªå·±çš„åˆ¤æ–­åªç»™å‡ºæˆªå–çš„éƒ¨åˆ†ã€?          required: true
        - label: æˆ‘æœç´¢äº† issues, æ²¡æœ‰å‘ç°å·²æå‡ºçš„ç±»ä¼¼é—®é¢˜ã€?          required: true
        - label: é—®é¢˜åœ?Release æœ€æ–°çš„ç‰ˆæœ¬ä¸Šå¯ä»¥æˆåŠŸå¤ç?          required: true
  - type: textarea
    attributes:
      label: æè¿°
      description: |-
        è¯·æä¾›é”™è¯¯çš„è¯¦ç»†æè¿°ã€‚ä»¥åŠä½ è®¤ä¸ºæœ‰ä»·å€¼çš„ä¿¡æ¯ã€?        å¦‚æœé—®é¢˜åœ¨æ›´æ–°åå‡ºç°ï¼Œè¯·æä¾›**å…·ä½“**å‡ºç°é—®é¢˜çš„ç‰ˆæœ¬å·ã€?    validations:
      required: true
  - type: textarea
    attributes:
      label: é‡ç°æ–¹å¼
      description: |-
        åŸºäºä½ ä¸‹é¢æä¾›çš„é…ç½®ï¼Œæä¾›é‡ç°BUGæ–¹æ³•ã€?    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## é…ç½®ä¸æ—¥å¿—éƒ¨åˆ?        
        ### å¯¹äºé…ç½®æ–‡ä»¶
        è¯·æä¾›å¯ä»¥é‡ç°é—®é¢˜çš„é…ç½®æ–‡ä»¶ï¼ŒåŒ…æ‹¬æœåŠ¡ç«¯å’Œå®¢æˆ·ç«¯ã€?        ä¸è¦ç›´æ¥åœ¨è¿™é‡Œé»è´´ä¸€å¤§æ®µå¯¼å‡ºçš?config æ–‡ä»¶ã€‚å»æ‰æ— ç”¨çš„å‡ºå…¥ç«™ã€è§„åˆ™ã€é€‰é¡¹ï¼Œè¿™å¯ä»¥å¸®åŠ©ç¡®å®šé—®é¢˜ï¼Œå¦‚æœä½ çœŸçš„æƒ³å¾—åˆ°å¸®åŠ©ã€?        
        ### å¯¹äºæ—¥å¿—
        è¯·å…ˆå°†æ—¥å¿—ç­‰çº§è®¾ç½®ä¸º debug, dnsLog è®¾ç½®ä¸ºtrue.
        é‡å¯ Xray-core ï¼Œå†æŒ‰å¤ç°æ–¹å¼æ“ä½œï¼Œå°½é‡å‡å°‘æ—¥å¿—ä¸­çš„æ— å…³éƒ¨åˆ†ã€?        è®°å¾—åˆ é™¤æœ‰å…³ä¸ªäººä¿¡æ¯ï¼ˆå¦‚UUIDä¸IPï¼‰çš„éƒ¨åˆ†ã€?        æä¾› Xray-core çš„æ—¥å¿—ï¼Œè€Œä¸æ˜¯é¢æ¿æˆ–è€…åˆ«çš„ä¸œè¥¿è¾“å‡ºçš„æ—¥å¿—ã€?
        ### æœ€å?        åœ¨å»æ‰ä¸å½±å“å¤ç°çš„éƒ¨åˆ†åï¼Œæä¾›å®é™…è¿è¡Œçš„**å®Œæ•´**æ–‡ä»¶ï¼Œä¸è¦å‡ºäºè‡ªå·±çš„åˆ¤æ–­åªæä¾›å…¥ç«™å‡ºç«™æˆ–è€…å‡ è¡Œæ—¥å¿—ã€?        æŠŠå†…å®¹æ”¾åœ¨æ–‡æœ¬æ¡†é¢„ç½®çš?```<details><pre><code>``` å’?```</code></pre></details>``` ä¸­é—´ã€?        å¦‚æœé—®é¢˜ååˆ†æ˜ç¡®åªå‡ºç°åœ¨æŸä¸€ç«?å¦‚æŒ‰æ–‡æ¡£æ­£ç¡®ç¼–å†™é…ç½®åæ ¸å¿ƒå¯åŠ¨å¤±è´?å´©æºƒ)ï¼Œå¯ä»¥åœ¨ä¸‹é¢ä¸éœ€è¦çš„é¡¹ç›®å¡«å…¥N/A.
  - type: textarea
    attributes:
      label: å®¢æˆ·ç«¯é…ç½?      value: |-
        <details><pre><code>

        </code></pre></details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: æœåŠ¡ç«¯é…ç½?      value: |-
        <details><pre><code>

        </code></pre></details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: å®¢æˆ·ç«¯æ—¥å¿?      value: |-
        <details><pre><code>

        </code></pre></details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: æœåŠ¡ç«¯æ—¥å¿?      value: |-
        <details><pre><code>

        </code></pre></details>
    validations:
      required: true
