contact_links:
  - name: Community Support and Questions
    url: https://github.com/hosemorinho412/Xray-core/discussions
    about: Please ask and answer questions there. The issue tracker is for issues with core.
