// Package oapi_gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package oapi_gen

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error RFC 9457 problem details.
type Error struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// JSON Arbitrary JSON object owned by the validator implementation.
type JSON map[string]interface{}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UsersCount defines model for UsersCount.
type UsersCount struct {
	Count int64 `json:"count"`
}

// VlessUser JSON representation of protocol.MemoryUser.
type VlessUser struct {
	// Account Arbitrary JSON object owned by the validator implementation.
	Account JSON `json:"account"`

	// Email User email. Must be unique when provided.
	Email *string `json:"email,omitempty"`

	// Level User policy level.
	Level *uint32 `json:"level,omitempty"`
}

// Email defines model for Email.
type Email = string

// BadRequest RFC 9457 problem details.
type BadRequest = Error

// GetUserResponse JSON representation of protocol.MemoryUser.
type GetUserResponse = VlessUser

// GetUsersCountResponse defines model for GetUsersCountResponse.
type GetUsersCountResponse = UsersCount

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse = []VlessUser

// InternalServerError RFC 9457 problem details.
type InternalServerError = Error

// UserAlreadyExists RFC 9457 problem details.
type UserAlreadyExists = Error

// UserCreated JSON representation of protocol.MemoryUser.
type UserCreated = VlessUser

// UserNotFound RFC 9457 problem details.
type UserNotFound = Error

// AddVlessUserJSONRequestBody defines body for AddVlessUser for application/json ContentType.
type AddVlessUserJSONRequestBody = VlessUser
