// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transport/internet/finalmask/header/custom/config.proto

package custom

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TCPItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DelayMin      int64                  `protobuf:"varint,1,opt,name=delay_min,json=delayMin,proto3" json:"delay_min,omitempty"`
	DelayMax      int64                  `protobuf:"varint,2,opt,name=delay_max,json=delayMax,proto3" json:"delay_max,omitempty"`
	Rand          int32                  `protobuf:"varint,3,opt,name=rand,proto3" json:"rand,omitempty"`
	Packet        []byte                 `protobuf:"bytes,4,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPItem) Reset() {
	*x = TCPItem{}
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPItem) ProtoMessage() {}

func (x *TCPItem) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPItem.ProtoReflect.Descriptor instead.
func (*TCPItem) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP(), []int{0}
}

func (x *TCPItem) GetDelayMin() int64 {
	if x != nil {
		return x.DelayMin
	}
	return 0
}

func (x *TCPItem) GetDelayMax() int64 {
	if x != nil {
		return x.DelayMax
	}
	return 0
}

func (x *TCPItem) GetRand() int32 {
	if x != nil {
		return x.Rand
	}
	return 0
}

func (x *TCPItem) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

type TCPSequence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      []*TCPItem             `protobuf:"bytes,1,rep,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPSequence) Reset() {
	*x = TCPSequence{}
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPSequence) ProtoMessage() {}

func (x *TCPSequence) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPSequence.ProtoReflect.Descriptor instead.
func (*TCPSequence) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP(), []int{1}
}

func (x *TCPSequence) GetSequence() []*TCPItem {
	if x != nil {
		return x.Sequence
	}
	return nil
}

type TCPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*TCPSequence         `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Servers       []*TCPSequence         `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	Errors        []*TCPSequence         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPConfig) Reset() {
	*x = TCPConfig{}
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPConfig) ProtoMessage() {}

func (x *TCPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPConfig.ProtoReflect.Descriptor instead.
func (*TCPConfig) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP(), []int{2}
}

func (x *TCPConfig) GetClients() []*TCPSequence {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *TCPConfig) GetServers() []*TCPSequence {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *TCPConfig) GetErrors() []*TCPSequence {
	if x != nil {
		return x.Errors
	}
	return nil
}

type UDPItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rand          int32                  `protobuf:"varint,1,opt,name=rand,proto3" json:"rand,omitempty"`
	Packet        []byte                 `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPItem) Reset() {
	*x = UDPItem{}
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPItem) ProtoMessage() {}

func (x *UDPItem) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPItem.ProtoReflect.Descriptor instead.
func (*UDPItem) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP(), []int{3}
}

func (x *UDPItem) GetRand() int32 {
	if x != nil {
		return x.Rand
	}
	return 0
}

func (x *UDPItem) GetPacket() []byte {
	if x != nil {
		return x.Packet
	}
	return nil
}

type UDPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        []*UDPItem             `protobuf:"bytes,1,rep,name=client,proto3" json:"client,omitempty"`
	Server        []*UDPItem             `protobuf:"bytes,2,rep,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UDPConfig) Reset() {
	*x = UDPConfig{}
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UDPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDPConfig) ProtoMessage() {}

func (x *UDPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_finalmask_header_custom_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDPConfig.ProtoReflect.Descriptor instead.
func (*UDPConfig) Descriptor() ([]byte, []int) {
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP(), []int{4}
}

func (x *UDPConfig) GetClient() []*UDPItem {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *UDPConfig) GetServer() []*UDPItem {
	if x != nil {
		return x.Server
	}
	return nil
}

var File_transport_internet_finalmask_header_custom_config_proto protoreflect.FileDescriptor

const file_transport_internet_finalmask_header_custom_config_proto_rawDesc = "" +
	"\n" +
	"7transport/internet/finalmask/header/custom/config.proto\x12/xray.transport.internet.finalmask.header.custom\"o\n" +
	"\aTCPItem\x12\x1b\n" +
	"\tdelay_min\x18\x01 \x01(\x03R\bdelayMin\x12\x1b\n" +
	"\tdelay_max\x18\x02 \x01(\x03R\bdelayMax\x12\x12\n" +
	"\x04rand\x18\x03 \x01(\x05R\x04rand\x12\x16\n" +
	"\x06packet\x18\x04 \x01(\fR\x06packet\"c\n" +
	"\vTCPSequence\x12T\n" +
	"\bsequence\x18\x01 \x03(\v28.xray.transport.internet.finalmask.header.custom.TCPItemR\bsequence\"\x91\x02\n" +
	"\tTCPConfig\x12V\n" +
	"\aclients\x18\x01 \x03(\v2<.xray.transport.internet.finalmask.header.custom.TCPSequenceR\aclients\x12V\n" +
	"\aservers\x18\x02 \x03(\v2<.xray.transport.internet.finalmask.header.custom.TCPSequenceR\aservers\x12T\n" +
	"\x06errors\x18\x03 \x03(\v2<.xray.transport.internet.finalmask.header.custom.TCPSequenceR\x06errors\"5\n" +
	"\aUDPItem\x12\x12\n" +
	"\x04rand\x18\x01 \x01(\x05R\x04rand\x12\x16\n" +
	"\x06packet\x18\x02 \x01(\fR\x06packet\"\xaf\x01\n" +
	"\tUDPConfig\x12P\n" +
	"\x06client\x18\x01 \x03(\v28.xray.transport.internet.finalmask.header.custom.UDPItemR\x06client\x12P\n" +
	"\x06server\x18\x02 \x03(\v28.xray.transport.internet.finalmask.header.custom.UDPItemR\x06serverB\xaf\x01\n" +
	"3com.xray.transport.internet.finalmask.header.customP\x01ZDgithub.com/xtls/xray-core/transport/internet/finalmask/header/custom\xaa\x02/Xray.Transport.Internet.Finalmask.Header.Customb\x06proto3"

var (
	file_transport_internet_finalmask_header_custom_config_proto_rawDescOnce sync.Once
	file_transport_internet_finalmask_header_custom_config_proto_rawDescData []byte
)

func file_transport_internet_finalmask_header_custom_config_proto_rawDescGZIP() []byte {
	file_transport_internet_finalmask_header_custom_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_finalmask_header_custom_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_finalmask_header_custom_config_proto_rawDesc), len(file_transport_internet_finalmask_header_custom_config_proto_rawDesc)))
	})
	return file_transport_internet_finalmask_header_custom_config_proto_rawDescData
}

var file_transport_internet_finalmask_header_custom_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_transport_internet_finalmask_header_custom_config_proto_goTypes = []any{
	(*TCPItem)(nil),     // 0: xray.transport.internet.finalmask.header.custom.TCPItem
	(*TCPSequence)(nil), // 1: xray.transport.internet.finalmask.header.custom.TCPSequence
	(*TCPConfig)(nil),   // 2: xray.transport.internet.finalmask.header.custom.TCPConfig
	(*UDPItem)(nil),     // 3: xray.transport.internet.finalmask.header.custom.UDPItem
	(*UDPConfig)(nil),   // 4: xray.transport.internet.finalmask.header.custom.UDPConfig
}
var file_transport_internet_finalmask_header_custom_config_proto_depIdxs = []int32{
	0, // 0: xray.transport.internet.finalmask.header.custom.TCPSequence.sequence:type_name -> xray.transport.internet.finalmask.header.custom.TCPItem
	1, // 1: xray.transport.internet.finalmask.header.custom.TCPConfig.clients:type_name -> xray.transport.internet.finalmask.header.custom.TCPSequence
	1, // 2: xray.transport.internet.finalmask.header.custom.TCPConfig.servers:type_name -> xray.transport.internet.finalmask.header.custom.TCPSequence
	1, // 3: xray.transport.internet.finalmask.header.custom.TCPConfig.errors:type_name -> xray.transport.internet.finalmask.header.custom.TCPSequence
	3, // 4: xray.transport.internet.finalmask.header.custom.UDPConfig.client:type_name -> xray.transport.internet.finalmask.header.custom.UDPItem
	3, // 5: xray.transport.internet.finalmask.header.custom.UDPConfig.server:type_name -> xray.transport.internet.finalmask.header.custom.UDPItem
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_transport_internet_finalmask_header_custom_config_proto_init() }
func file_transport_internet_finalmask_header_custom_config_proto_init() {
	if File_transport_internet_finalmask_header_custom_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_finalmask_header_custom_config_proto_rawDesc), len(file_transport_internet_finalmask_header_custom_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_finalmask_header_custom_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_finalmask_header_custom_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_finalmask_header_custom_config_proto_msgTypes,
	}.Build()
	File_transport_internet_finalmask_header_custom_config_proto = out.File
	file_transport_internet_finalmask_header_custom_config_proto_goTypes = nil
	file_transport_internet_finalmask_header_custom_config_proto_depIdxs = nil
}
