// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: app/connectiontracker/command/command.proto

package command

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	ConnTrackerService_ListConnections_FullMethodName   = "/xray.app.connectiontracker.command.ConnTrackerService/ListConnections"
	ConnTrackerService_CloseConnection_FullMethodName   = "/xray.app.connectiontracker.command.ConnTrackerService/CloseConnection"
	ConnTrackerService_GetUserStats_FullMethodName      = "/xray.app.connectiontracker.command.ConnTrackerService/GetUserStats"
	ConnTrackerService_StreamConnections_FullMethodName = "/xray.app.connectiontracker.command.ConnTrackerService/StreamConnections"
)

// ConnTrackerServiceClient is the client API for ConnTrackerService service.
type ConnTrackerServiceClient interface {
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error)
	GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error)
	StreamConnections(ctx context.Context, in *StreamConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionUpdate], error)
}

type connTrackerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnTrackerServiceClient(cc grpc.ClientConnInterface) ConnTrackerServiceClient {
	return &connTrackerServiceClient{cc}
}

func (c *connTrackerServiceClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, ConnTrackerService_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connTrackerServiceClient) CloseConnection(ctx context.Context, in *CloseConnectionRequest, opts ...grpc.CallOption) (*CloseConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseConnectionResponse)
	err := c.cc.Invoke(ctx, ConnTrackerService_CloseConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connTrackerServiceClient) GetUserStats(ctx context.Context, in *GetUserStatsRequest, opts ...grpc.CallOption) (*GetUserStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserStatsResponse)
	err := c.cc.Invoke(ctx, ConnTrackerService_GetUserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connTrackerServiceClient) StreamConnections(ctx context.Context, in *StreamConnectionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnTrackerService_ServiceDesc.Streams[0], ConnTrackerService_StreamConnections_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConnectionsRequest, ConnectionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnTrackerService_StreamConnectionsClient = grpc.ServerStreamingClient[ConnectionUpdate]

// ConnTrackerServiceServer is the server API for ConnTrackerService service.
// All implementations must embed UnimplementedConnTrackerServiceServer
// for forward compatibility.
type ConnTrackerServiceServer interface {
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error)
	GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error)
	StreamConnections(*StreamConnectionsRequest, grpc.ServerStreamingServer[ConnectionUpdate]) error
	mustEmbedUnimplementedConnTrackerServiceServer()
}

// UnimplementedConnTrackerServiceServer must be embedded to have
// forward compatible implementations.
type UnimplementedConnTrackerServiceServer struct{}

func (UnimplementedConnTrackerServiceServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedConnTrackerServiceServer) CloseConnection(context.Context, *CloseConnectionRequest) (*CloseConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseConnection not implemented")
}
func (UnimplementedConnTrackerServiceServer) GetUserStats(context.Context, *GetUserStatsRequest) (*GetUserStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserStats not implemented")
}
func (UnimplementedConnTrackerServiceServer) StreamConnections(*StreamConnectionsRequest, grpc.ServerStreamingServer[ConnectionUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamConnections not implemented")
}
func (UnimplementedConnTrackerServiceServer) mustEmbedUnimplementedConnTrackerServiceServer() {}
func (UnimplementedConnTrackerServiceServer) testEmbeddedByValue()                            {}

// UnsafeConnTrackerServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeConnTrackerServiceServer interface {
	mustEmbedUnimplementedConnTrackerServiceServer()
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnTrackerService_StreamConnectionsServer = grpc.ServerStreamingServer[ConnectionUpdate]

func RegisterConnTrackerServiceServer(s grpc.ServiceRegistrar, srv ConnTrackerServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnTrackerService_ServiceDesc, srv)
}

func _ConnTrackerService_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnTrackerServiceServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnTrackerService_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnTrackerServiceServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnTrackerService_CloseConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnTrackerServiceServer).CloseConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnTrackerService_CloseConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnTrackerServiceServer).CloseConnection(ctx, req.(*CloseConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnTrackerService_GetUserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnTrackerServiceServer).GetUserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnTrackerService_GetUserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnTrackerServiceServer).GetUserStats(ctx, req.(*GetUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnTrackerService_StreamConnections_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConnectionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnTrackerServiceServer).StreamConnections(m, &grpc.GenericServerStream[StreamConnectionsRequest, ConnectionUpdate]{ServerStream: stream})
}

// ConnTrackerService_ServiceDesc is the grpc.ServiceDesc for ConnTrackerService service.
var ConnTrackerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.connectiontracker.command.ConnTrackerService",
	HandlerType: (*ConnTrackerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnections",
			Handler:    _ConnTrackerService_ListConnections_Handler,
		},
		{
			MethodName: "CloseConnection",
			Handler:    _ConnTrackerService_CloseConnection_Handler,
		},
		{
			MethodName: "GetUserStats",
			Handler:    _ConnTrackerService_GetUserStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConnections",
			Handler:       _ConnTrackerService_StreamConnections_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/connectiontracker/command/command.proto",
}
