// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transport/internet/champa/config.proto

package champa

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_url is the absolute URL of the champa server, e.g.
	// "https://example.com/champa/". Client only.
	ServerUrl string `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	// cache_url is the AMP cache URL, e.g. "https://cdn.ampproject.org/".
	// Empty means no cache (talk to server_url directly). Client only.
	CacheUrl string `protobuf:"bytes,2,opt,name=cache_url,json=cacheUrl,proto3" json:"cache_url,omitempty"`
	// front is the domain to use for the actual TCP connection / SNI / Host
	// header. Empty means no fronting. Client only.
	Front string `protobuf:"bytes,3,opt,name=front,proto3" json:"front,omitempty"`
	// pubkey is the server's Noise NK public key, hex-encoded (64 chars).
	// Client only.
	Pubkey string `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// privkey is the server's Noise NK private key, hex-encoded (64 chars).
	// Server only.
	Privkey       string `protobuf:"bytes,5,opt,name=privkey,proto3" json:"privkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_champa_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_champa_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_champa_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *Config) GetCacheUrl() string {
	if x != nil {
		return x.CacheUrl
	}
	return ""
}

func (x *Config) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *Config) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Config) GetPrivkey() string {
	if x != nil {
		return x.Privkey
	}
	return ""
}

var File_transport_internet_champa_config_proto protoreflect.FileDescriptor

const file_transport_internet_champa_config_proto_rawDesc = "" +
	"\n" +
	"&transport/internet/champa/config.proto\x12\x1exray.transport.internet.champa\"\x8c\x01\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"server_url\x18\x01 \x01(\tR\tserverUrl\x12\x1b\n" +
	"\tcache_url\x18\x02 \x01(\tR\bcacheUrl\x12\x14\n" +
	"\x05front\x18\x03 \x01(\tR\x05front\x12\x16\n" +
	"\x06pubkey\x18\x04 \x01(\tR\x06pubkey\x12\x18\n" +
	"\aprivkey\x18\x05 \x01(\tR\aprivkeyB|\n" +
	"\"com.xray.transport.internet.champaP\x01Z3github.com/xtls/xray-core/transport/internet/champa\xaa\x02\x1eXray.Transport.Internet.Champab\x06proto3"

var (
	file_transport_internet_champa_config_proto_rawDescOnce sync.Once
	file_transport_internet_champa_config_proto_rawDescData []byte
)

func file_transport_internet_champa_config_proto_rawDescGZIP() []byte {
	file_transport_internet_champa_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_champa_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_champa_config_proto_rawDesc), len(file_transport_internet_champa_config_proto_rawDesc)))
	})
	return file_transport_internet_champa_config_proto_rawDescData
}

var file_transport_internet_champa_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transport_internet_champa_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.transport.internet.champa.Config
}
var file_transport_internet_champa_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transport_internet_champa_config_proto_init() }
func file_transport_internet_champa_config_proto_init() {
	if File_transport_internet_champa_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_champa_config_proto_rawDesc), len(file_transport_internet_champa_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_champa_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_champa_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_champa_config_proto_msgTypes,
	}.Build()
	File_transport_internet_champa_config_proto = out.File
	file_transport_internet_champa_config_proto_goTypes = nil
	file_transport_internet_champa_config_proto_depIdxs = nil
}
