#!/bin/bash

FAIL=0

XRAY_OUT=${PWD}/out/xray
export XRAY_COV=${XRAY_OUT}/cov
COVERAGE_FILE=${XRAY_COV}/coverage.txt

function test_package {
  DIR=".$1"
  DEP=$(go list -f '{{ join .Deps "\n" }}' $DIR | grep xray | tr '\n' ',')
  DEP=${DEP}$DIR
  RND_NAME=$(openssl rand -hex 16)
  COV_PROFILE=${XRAY_COV}/${RND_NAME}.out
  go test -tags "json coverage" -coverprofile=${COV_PROFILE} -coverpkg=$DEP $DIR || FAIL=1
}

rm -rf ${XRAY_OUT}
mkdir -p ${XRAY_COV}
touch ${COVERAGE_FILE}

TEST_FILES=(./*_test.go)
if [ -f ${TEST_FILES[0]} ]; then
  test_package ""
fi

for DIR in $(find * -type d ! -path "*.git*" ! -path "*vendor*" ! -path "*external*"); do
  TEST_FILES=($DIR/*_test.go)
  if [ -f ${TEST_FILES[0]} ]; then
    test_package "/$DIR"
  fi
done

for OUT_FILE in $(find ${XRAY_COV} -name "*.out"); do
  echo "Merging file ${OUT_FILE}"
  cat ${OUT_FILE} | grep -v "mode: set" >> ${COVERAGE_FILE}
done

COV_SORTED=${XRAY_COV}/coverallsorted.out
cat ${COVERAGE_FILE} | sort -t: -k1 | grep -vw "testing" | grep -v ".pb.go" | grep -vw "vendor" | grep -vw "external" > ${COV_SORTED}
echo "mode: set" | cat - ${COV_SORTED} > ${COVERAGE_FILE}

if [ "$FAIL" -eq 0 ]; then
  echo "Uploading coverage datea to codecov."
  #bash <(curl -s https://codecov.io/bash) -f ${COVERAGE_FILE} -v || echo "Codecov did not collect coverage reports."
fi

exit $FAIL
