// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/mieru/config.proto

package mieru

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Server        *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Transport     string                   `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	Mtu           int32                    `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Multiplexing  string                   `protobuf:"bytes,4,opt,name=multiplexing,proto3" json:"multiplexing,omitempty"`
	HandshakeMode int32                    `protobuf:"varint,5,opt,name=handshake_mode,json=handshakeMode,proto3" json:"handshake_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ClientConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ClientConfig) GetMultiplexing() string {
	if x != nil {
		return x.Multiplexing
	}
	return ""
}

func (x *ClientConfig) GetHandshakeMode() int32 {
	if x != nil {
		return x.HandshakeMode
	}
	return 0
}

type ServerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Users               []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Mtu                 int32                  `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	UserHintIsMandatory bool                   `protobuf:"varint,3,opt,name=user_hint_is_mandatory,json=userHintIsMandatory,proto3" json:"user_hint_is_mandatory,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ServerConfig) GetUserHintIsMandatory() bool {
	if x != nil {
		return x.UserHintIsMandatory
	}
	return false
}

var File_proxy_mieru_config_proto protoreflect.FileDescriptor

const file_proxy_mieru_config_proto_rawDesc = "" +
	"\n" +
	"\x18proxy/mieru/config.proto\x12\x10xray.proxy.mieru\x1a!common/protocol/server_spec.proto\x1a\x1acommon/protocol/user.proto\"\xc7\x01\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06server\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\x05R\x03mtu\x12\"\n" +
	"\fmultiplexing\x18\x04 \x01(\tR\fmultiplexing\x12%\n" +
	"\x0ehandshake_mode\x18\x05 \x01(\x05R\rhandshakeMode\"\x87\x01\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12\x10\n" +
	"\x03mtu\x18\x02 \x01(\x05R\x03mtu\x123\n" +
	"\x16user_hint_is_mandatory\x18\x03 \x01(\bR\x13userHintIsMandatoryBR\n" +
	"\x14com.xray.proxy.mieruP\x01Z%github.com/xtls/xray-core/proxy/mieru\xaa\x02\x10Xray.Proxy.Mierub\x06proto3"

var (
	file_proxy_mieru_config_proto_rawDescOnce sync.Once
	file_proxy_mieru_config_proto_rawDescData []byte
)

func file_proxy_mieru_config_proto_rawDescGZIP() []byte {
	file_proxy_mieru_config_proto_rawDescOnce.Do(func() {
		file_proxy_mieru_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)))
	})
	return file_proxy_mieru_config_proto_rawDescData
}

var file_proxy_mieru_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_mieru_config_proto_goTypes = []any{
	(*ClientConfig)(nil),            // 0: xray.proxy.mieru.ClientConfig
	(*ServerConfig)(nil),            // 1: xray.proxy.mieru.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 2: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 3: xray.common.protocol.User
}
var file_proxy_mieru_config_proto_depIdxs = []int32{
	2, // 0: xray.proxy.mieru.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	3, // 1: xray.proxy.mieru.ServerConfig.users:type_name -> xray.common.protocol.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_mieru_config_proto_init() }
func file_proxy_mieru_config_proto_init() {
	if File_proxy_mieru_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mieru_config_proto_goTypes,
		DependencyIndexes: file_proxy_mieru_config_proto_depIdxs,
		MessageInfos:      file_proxy_mieru_config_proto_msgTypes,
	}.Build()
	File_proxy_mieru_config_proto = out.File
	file_proxy_mieru_config_proto_goTypes = nil
	file_proxy_mieru_config_proto_depIdxs = nil
}
