syntax = "proto3";

package xray.proxy.masque;
option csharp_namespace = "Xray.Proxy.Masque";
option go_package = "github.com/xtls/xray-core/proxy/masque";
option java_package = "com.xray.proxy.masque";
option java_multiple_files = true;

import "common/protocol/server_spec.proto";
import "common/protocol/user.proto";

message ClientConfig {
  xray.common.protocol.ServerEndpoint server = 1;
  repeated string remote_dns = 2;
}

message Account {
  string password = 1;
}

message ServerConfig {
  repeated xray.common.protocol.User users = 1;
  repeated string address = 2;
  uint32 mtu = 3;
}
