package monitor

import (
	. "github.com/amirdlt/flex/util"
	"regexp"
)

var categoryToTagRegex = Map[string, Map[string, *regexp.Regexp]]{
	"social_media": {
		"whatsapp":        regexp.MustCompile(`whatsapp`),
		"facebook":        regexp.MustCompile(`facebook`),
		"instagram":       regexp.MustCompile(`instagram`),
		"snapchat":        regexp.MustCompile(`snapchat`),
		"reddit":          regexp.MustCompile(`reddit`),
		"linkedin":        regexp.MustCompile(`linkedin`),
		"pinterest":       regexp.MustCompile(`pinterest`),
		"tumblr":          regexp.MustCompile(`tumblr`),
		"wechat":          regexp.MustCompile(`wechat`),
		"vk":              regexp.MustCompile(`vk\.com`),
		"quora":           regexp.MustCompile(`quora`),
		"flickr":          regexp.MustCompile(`flickr`),
		"telegram":        regexp.MustCompile(`telegram`),
		"x":               regexp.MustCompile(`x\.com|twitter`),
		"discord":         regexp.MustCompile(`discord`),
		"tiktok":          regexp.MustCompile(`tiktok`),
		"youtube":         regexp.MustCompile(`youtube`),
		"weibo":           regexp.MustCompile(`weibo`),
		"qq":              regexp.MustCompile(`qq\.com`),
		"tencent":         regexp.MustCompile(`tencent`),
		"kakao":           regexp.MustCompile(`kakao`),
		"tinder":          regexp.MustCompile(`tinder`),
		"badoo":           regexp.MustCompile(`badoo`),
		"skype":           regexp.MustCompile(`skype`),
		"slack":           regexp.MustCompile(`slack`),
		"microsoft_teams": regexp.MustCompile(`teams\.microsoft`),
		"clubhouse":       regexp.MustCompile(`clubhouse`),
	},
	"porn": {
		"pornhub":           regexp.MustCompile(`pornhub`),
		"xnxx":              regexp.MustCompile(`xnxx`),
		"xvideos":           regexp.MustCompile(`xvideos`),
		"redtube":           regexp.MustCompile(`redtube`),
		"tube8":             regexp.MustCompile(`tube8`),
		"youporn":           regexp.MustCompile(`youporn`),
		"onlyfans":          regexp.MustCompile(`onlyfans`),
		"chaturbate":        regexp.MustCompile(`chaturbate`),
		"youjizz":           regexp.MustCompile(`youjizz`),
		"spankbang":         regexp.MustCompile(`spankbang`),
		"livejasmin":        regexp.MustCompile(`livejasmin`),
		"camsoda":           regexp.MustCompile(`camsoda`),
		"brazzers":          regexp.MustCompile(`brazzers`),
		"playboy":           regexp.MustCompile(`playboy`),
		"naughtyamerica":    regexp.MustCompile(`naughtyamerica`),
		"adultfriendfinder": regexp.MustCompile(`adultfriendfinder`),
		"porn":              regexp.MustCompile(`porn`),
	},
	"entertainment": {
		"netflix":       regexp.MustCompile(`netflix`),
		"hulu":          regexp.MustCompile(`hulu`),
		"disneyplus":    regexp.MustCompile(`disney\+|disneyplus`),
		"amazon_prime":  regexp.MustCompile(`primevideo|prime\.amazon`),
		"twitch":        regexp.MustCompile(`twitch`),
		"youtube":       regexp.MustCompile(`youtube`),
		"dailymotion":   regexp.MustCompile(`dailymotion`),
		"hbomax":        regexp.MustCompile(`hbomax|hbo`),
		"paramountplus": regexp.MustCompile(`paramount\+|paramountplus`),
		"peacock":       regexp.MustCompile(`peacocktv`),
		"apple_tv":      regexp.MustCompile(`apple\.com/tv`),
		"crunchyroll":   regexp.MustCompile(`crunchyroll`),
		"vimeo":         regexp.MustCompile(`vimeo`),
	},
	"music": {
		"spotify":     regexp.MustCompile(`spotify`),
		"apple_music": regexp.MustCompile(`applemusic|itunes`),
		"soundcloud":  regexp.MustCompile(`soundcloud`),
		"deezer":      regexp.MustCompile(`deezer`),
		"pandora":     regexp.MustCompile(`pandora`),
		"tidal":       regexp.MustCompile(`tidal`),
		"lastfm":      regexp.MustCompile(`last\.fm`),
		"bandcamp":    regexp.MustCompile(`bandcamp`),
	},
	"gaming": {
		"steam":               regexp.MustCompile(`steampowered\.com|steamcommunity`),
		"epic_games":          regexp.MustCompile(`epicgames`),
		"origin":              regexp.MustCompile(`origin\.com`),
		"uplay":               regexp.MustCompile(`uplay|ubisoft`),
		"battle_net":          regexp.MustCompile(`battle\.net`),
		"playstation_network": regexp.MustCompile(`playstation`),
		"xbox_live":           regexp.MustCompile(`xbox`),
		"nintendo":            regexp.MustCompile(`nintendo`),
		"roblox":              regexp.MustCompile(`roblox`),
		"minecraft":           regexp.MustCompile(`minecraft`),
		"fortnite":            regexp.MustCompile(`fortnite`),
	},
	"messaging": {
		"whatsapp":           regexp.MustCompile(`whatsapp`),
		"telegram":           regexp.MustCompile(`telegram`),
		"wechat":             regexp.MustCompile(`wechat`),
		"line":               regexp.MustCompile(`line\.me`),
		"signal":             regexp.MustCompile(`signal`),
		"viber":              regexp.MustCompile(`viber`),
		"discord":            regexp.MustCompile(`discord`),
		"facebook_messenger": regexp.MustCompile(`messenger\.com`),
		"kik":                regexp.MustCompile(`kik\.com`),
		"google_hangouts":    regexp.MustCompile(`hangouts\.google`),
		"skype":              regexp.MustCompile(`skype`),
		"slack":              regexp.MustCompile(`slack`),
		"zoom":               regexp.MustCompile(`zoom`),
		"meet":               regexp.MustCompile(`meet\.google`),
		"microsoft_teams":    regexp.MustCompile(`teams\.microsoft`),
	},
	"search_engines": {
		"google":       regexp.MustCompile(`google`),
		"bing":         regexp.MustCompile(`bing`),
		"duckduckgo":   regexp.MustCompile(`duckduckgo`),
		"yahoo":        regexp.MustCompile(`yahoo`),
		"baidu":        regexp.MustCompile(`baidu`),
		"ask":          regexp.MustCompile(`ask\.com`),
		"yandex":       regexp.MustCompile(`yandex`),
		"wolframalpha": regexp.MustCompile(`wolframalpha`),
		"ecosia":       regexp.MustCompile(`ecosia`),
	},
	"ecommerce": {
		"amazon":     regexp.MustCompile(`amazon`),
		"ebay":       regexp.MustCompile(`ebay`),
		"alibaba":    regexp.MustCompile(`alibaba`),
		"aliexpress": regexp.MustCompile(`aliexpress`),
		"etsy":       regexp.MustCompile(`etsy`),
		"rakuten":    regexp.MustCompile(`rakuten`),
		"walmart":    regexp.MustCompile(`walmart`),
		"target":     regexp.MustCompile(`target`),
		"bestbuy":    regexp.MustCompile(`bestbuy`),
		"flipkart":   regexp.MustCompile(`flipkart`),
		"jd":         regexp.MustCompile(`jd\.com`),
		"shopify":    regexp.MustCompile(`shopify`),
		"zalando":    regexp.MustCompile(`zalando`),
	},
	"news": {
		"cnn":              regexp.MustCompile(`cnn`),
		"bbc":              regexp.MustCompile(`bbc`),
		"nytimes":          regexp.MustCompile(`nytimes|newyorktimes`),
		"theguardian":      regexp.MustCompile(`theguardian`),
		"foxnews":          regexp.MustCompile(`foxnews`),
		"washingtonpost":   regexp.MustCompile(`washingtonpost`),
		"reuters":          regexp.MustCompile(`reuters`),
		"huffpost":         regexp.MustCompile(`huffpost`),
		"aljazeera":        regexp.MustCompile(`aljazeera`),
		"bloomberg":        regexp.MustCompile(`bloomberg`),
		"forbes":           regexp.MustCompile(`forbes`),
		"business_insider": regexp.MustCompile(`businessinsider`),
		"cnbc":             regexp.MustCompile(`cnbc`),
		"msnbc":            regexp.MustCompile(`msnbc`),
		"time":             regexp.MustCompile(`time\.com`),
		"economist":        regexp.MustCompile(`economist`),
	},
	"cloud_providers": {
		"aws":          regexp.MustCompile(`amazonaws`),
		"azure":        regexp.MustCompile(`azure`),
		"google_cloud": regexp.MustCompile(`googleapis|gcloud|googlecloud`),
		"cloudflare":   regexp.MustCompile(`cloudflare`),
		"digitalocean": regexp.MustCompile(`digitalocean`),
		"linode":       regexp.MustCompile(`linode`),
		"heroku":       regexp.MustCompile(`heroku`),
		"oracle_cloud": regexp.MustCompile(`oraclecloud`),
		"aliyun":       regexp.MustCompile(`aliyun`),
	},
	"ai_tech": {
		"chatgpt":       regexp.MustCompile(`chatgpt|openai|poe`),
		"github":        regexp.MustCompile(`github`),
		"gitlab":        regexp.MustCompile(`gitlab`),
		"bitbucket":     regexp.MustCompile(`bitbucket`),
		"stackoverflow": regexp.MustCompile(`stackoverflow`),
		"medium":        regexp.MustCompile(`medium\.com`),
		"wikipedia":     regexp.MustCompile(`wikipedia`),
	},
	"education": {
		"coursera":     regexp.MustCompile(`coursera`),
		"edx":          regexp.MustCompile(`edx\.org`),
		"udemy":        regexp.MustCompile(`udemy`),
		"khan_academy": regexp.MustCompile(`khanacademy`),
		"udacity":      regexp.MustCompile(`udacity`),
		"skillshare":   regexp.MustCompile(`skillshare`),
	},
	"finance": {
		"paypal":    regexp.MustCompile(`paypal`),
		"stripe":    regexp.MustCompile(`stripe`),
		"coinbase":  regexp.MustCompile(`coinbase`),
		"binance":   regexp.MustCompile(`binance`),
		"robinhood": regexp.MustCompile(`robinhood`),
	},
	"isp": {
		"irancell":      regexp.MustCompile(`irancell`),
		"mci":           regexp.MustCompile(`mci|hamrahaval|hamraheaval|mci\.ir|mobile.communication.company.*iran`),
		"mokhaberat":    regexp.MustCompile(`mokhaberat|tci|telecommunication\s+company\s+of\s+iran`),
		"rightel":       regexp.MustCompile(`rightel`),
		"shatel":        regexp.MustCompile(`shatel`),
		"pars_online":   regexp.MustCompile(`parsonline|pars\s*online`),
		"hiweb":         regexp.MustCompile(`hiweb`),
		"afranet":       regexp.MustCompile(`afranet`),
		"asiatech":      regexp.MustCompile(`asiatech`),
		"mobinnet":      regexp.MustCompile(`mobinnet`),
		"zitel":         regexp.MustCompile(`zitel`),
		"netafraz":      regexp.MustCompile(`netafraz`),
		"pishgaman":     regexp.MustCompile(`pishgaman`),
		"samantel":      regexp.MustCompile(`samantel`),
		"fanap_telecom": regexp.MustCompile(`fanaptelecom|fanap`),
		"respina":       regexp.MustCompile(`respina`),
		"sibnet":        regexp.MustCompile(`sibnet`),
		"pardis":        regexp.MustCompile(`pardis`),
		"faratel":       regexp.MustCompile(`faratel`),
		"sepanta":       regexp.MustCompile(`sepanta`),
		"datak":         regexp.MustCompile(`datak`),
	},
}

func TagCategories() Stream[string] {
	return categoryToTagRegex.Keys()
}

func TagsOfACategory(category string) Stream[string] {
	return categoryToTagRegex.GetOrDefault(category, Map[string, *regexp.Regexp]{}).Keys()
}
