oapi-codegen:
	oapi-codegen --generate="client" --package="oapi_gen" -o="./oapi_gen/client.gen.go" "./rest.yaml"
	oapi-codegen --generate="types" --package="oapi_gen" -o="./oapi_gen/models.gen.go" "./rest.yaml"
