name: Tests and Checkings

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-assets:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
      - name: Restore Geodat Cache
        uses: actions/cache/restore@v6
        with:
          path: resources
          key: xray-geodat-
      - name: Prepare Geodat
        run: bash .github/build/prepare-assets.sh geodat
      - name: Upload prepared assets
        uses: actions/upload-artifact@v7
        with:
          name: prepared-assets
          path: resources/
          if-no-files-found: error

  check-proto:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
      - name: Check Proto Version Header
        run: |
          head -n 4 core/config.pb.go > ref.txt
          find . -name "*.pb.go" ! -name "*_grpc.pb.go" -print0 | while IFS= read -r -d '' file; do
            if ! cmp -s ref.txt <(head -n 4 "$file"); then
              echo "Error: Header mismatch in $file"
              head -n 4 "$file"
              exit 1
            fi
          done

  check-format:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    permissions:
      contents: read
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false
      - name: Check Format
        run: go run ./infra/vformat/main.go -mode check -pwd ./

  test:
    needs: check-assets
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Download prepared assets
        uses: actions/download-artifact@v8
        with:
          name: prepared-assets
          path: resources
      - name: Test
        run: go test -timeout 1h -v ./...
